### ISSUE TITLE
npm run start fails on Windows 8.1 ELIFECYCLE

### ISSUE THREAD

**Issue by ghost** [cloverfield-tools/universal-react-boilerplate#9] opened 2015-02-14 14:45 UTC
Here is my npm-debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart isomorphic-express-boilerplate@1.2.2
6 info start isomorphic-express-boilerplate@1.2.2
7 verbose unsafe-perm in lifecycle true
8 info isomorphic-express-boilerplate@1.2.2 Failed to exec start script
9 verbose stack Error: isomorphic-express-boilerplate@1.2.2 start: `node app/index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Users\Norbert\AppData\Roaming\nvm\v0.12.0\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Users\Norbert\AppData\Roaming\nvm\v0.12.0\node_modules\npm\lib\utils\spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid isomorphic-express-boilerplate@1.2.2
11 verbose cwd c:\Users\Norbert\Documents\GitHub\isomorphic-express-boilerplate
12 error Windows_NT 6.3.9600
13 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
14 error node v0.12.0
15 error npm  v2.5.1
16 error code ELIFECYCLE
17 error isomorphic-express-boilerplate@1.2.2 start: `node app/index.js`
17 error Exit status 1
18 error Failed at the isomorphic-express-boilerplate@1.2.2 start script 'node app/index.js'.
18 error This is most likely a problem with the isomorphic-express-boilerplate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node app/index.js
18 error You can get their info via:
18 error     npm owner ls isomorphic-express-boilerplate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Hope that helps.

**Comment by ericelliott** [comment] 2015-02-14 18:56
What terminal are you using?

Does it work in Git Bash?

**Comment by nfuhs** [comment] 2015-02-14 18:58
I tried Git Bash and Windows PowerShell.. it didn't work

**Comment by ericelliott** [comment] 2015-02-14 19:15
Did you get the same output from Git Bash?

**Comment by nfuhs** [comment] 2015-02-14 19:38
I check it once again wait a few minutes i have to boot my windows box..

**Comment by nfuhs** [comment] 2015-02-14 20:02
i tried it again with my windows box with git bash in the isomorphic-express-boilerplate folder
i ran npm run start and got this

0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart isomorphic-express-boilerplate@1.2.2
6 info start isomorphic-express-boilerplate@1.2.2
7 verbose unsafe-perm in lifecycle true
8 info isomorphic-express-boilerplate@1.2.2 Failed to exec start script
9 verbose stack Error: isomorphic-express-boilerplate@1.2.2 start: `node app/index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid isomorphic-express-boilerplate@1.2.2
11 verbose cwd c:\Users\Norbert\Documents\GitHub\isomorphic-express-boilerplate
12 error Windows_NT 6.3.9600
13 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
14 error node v0.12.0
15 error npm  v2.5.1
16 error code ELIFECYCLE
17 error isomorphic-express-boilerplate@1.2.2 start: `node app/index.js`
17 error Exit status 1
18 error Failed at the isomorphic-express-boilerplate@1.2.2 start script 'node app/index.js'.
18 error This is most likely a problem with the isomorphic-express-boilerplate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node app/index.js
18 error You can get their info via:
18 error     npm owner ls isomorphic-express-boilerplate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

and this is the same from PowerShell:

Windows PowerShell
Copyright (C) 2013 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Norbert\Documents\GitHub> cd .\isomorphic-express-boilerplate
C:\Users\Norbert\Documents\GitHub\isomorphic-express-boilerplate [master]> npm run start

> isomorphic-express-boilerplate@1.2.2 start C:\Users\Norbert\Documents\GitHub\isomorphic-express-boilerplate
> node app/index.js

module.js:489
    throw err;
          ^
SyntaxError: C:\Users\Norbert\Documents\GitHub\isomorphic-express-boilerplate\node_modules\express\node_modules\accepts\
node_modules\mime-types\node_modules\mime-db\db.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:486:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Norbert\Documents\GitHub\isomorphic-express-boilerplate\node_modules\express\node_mo
dules\accepts\node_modules\mime-types\node_modules\mime-db\index.js:11:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "r
un" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! isomorphic-express-boilerplate@1.2.2 start: `node app/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isomorphic-express-boilerplate@1.2.2 start script 'node app/index.js'.
npm ERR! This is most likely a problem with the isomorphic-express-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app/index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls isomorphic-express-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Norbert\Documents\GitHub\isomorphic-express-boilerplate\npm-debug.log
C:\Users\Norbert\Documents\GitHub\isomorphic-express-boilerplate [master]>

**Comment by ericelliott** [comment] 2015-02-14 22:03
Thanks a lot for the report! Looks like it probably has to do with path names. I'm surprised this isn't handled by `npm`. I'll see if I can provision a Windows machine to test on. =)

**Comment by ericelliott** [comment] 2015-02-14 22:08
Can you verify that you're using the most recent version of npm?

```
npm --version
```

[How to update npm to the latest version](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows).

**Comment by nfuhs** [comment] 2015-02-14 23:46
Welcome to Git (version 1.9.5-preview20141217)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

Norbert@SKYNET /C/Users/Norbert/Desktop
$ npm --version
2.5.1

**Comment by ericelliott** [comment] 2015-02-15 00:21
Do you want to try your hand at a pull request?

**Comment by nfuhs** [comment] 2015-02-15 00:29
i don't know anything about nodejs on windows... i normally use it under ubuntu... i will look what i can find on the net about issues running npm scripts under windows

**Comment by ericelliott** [comment] 2015-02-15 00:32
Thanks! =)

**Comment by nfuhs** [comment] 2015-02-15 00:35
but first i will take a nap.. its 01:34 AM here in Germany

**Comment by brakmic** [comment] 2015-02-15 00:47
According to this entry on StackOverflow ENOENT signals a path/location problem.

http://stackoverflow.com/questions/28425229/why-cant-execute-npm-start-or-even-other-npm-commands

**Comment by brakmic** [comment] 2015-02-15 00:52
Here, something similar. Instead of letting npm call the script one should run it manually (it seems to be a Windows-specific problem):

https://github.com/bitpay/insight/issues/559

**Comment by ericelliott** [comment] 2015-02-15 22:19
I have always recommended that Windows users use something like Nitrous.IO for developing Node apps. Maybe this is another great reason to do so...

**Comment by nfuhs** [comment] 2015-02-15 23:59
i think the solution to the problem is using the path module http://nodejs.org/api/path.html

**Comment by ericelliott** [comment] 2015-02-16 02:00
Interesting. Do you have more specific thoughts on it? Maybe a sample implementation?

We could create a scripts directory and just put all the scripts in there. Those scripts would use the path module to pass the parameters into all the sub processes...

**Comment by hurelu** [comment] 2015-05-24 04:07
For what it's worth, I have the following observation:
I have a simple mocha test script. If I run `npm test` everything works fine but if I run `npm run test` the script runs normally and then throws a chain of errors (ELIFECYCLE, Exit status 1).

I thought `npm test` would simply run `npm run test` internally but the results are actually different. What could explain this difference?
(windows 8.1, npm 2.7.4)

**Comment by ericelliott** [comment] 2015-05-24 16:33
I have no idea. Having no Windows box, I can't even try to reproduce these issues.

**Comment by hurelu** [comment] 2015-05-24 23:27
Had a look at the source code and I am quite sure the difference is in the callback provided. With `npm test` the callback is set to a simple `err` check and message. With `npm run test` a different callback is used but I could not figure out how the CLI interacts with lifecycle.js to provide the callback. Where do I look to find where the CLI converts `run-script(args)` to `npm.commands.run-script(args, callback)` with the added callback parameter?

**Comment by ericelliott** [comment] 2015-05-25 19:21
I think that's a question for the [npm team](https://github.com/npm/npm). =)

**Comment by ericelliott** [comment] 2015-11-11 00:38
I just rewrote the whole thing.

Can you try this again with the latest code and open a new issue if it's still a problem?

**Comment by MitjaBezensek** [comment] 2015-11-28 20:48
I just tried it now and I'm still having the same issue. Tried adding NODE_PATH to environment variables, but it didn't help. Tried Git Bash and Powershell with the same result.

**Comment by gacosta89** [comment] 2015-12-15 13:35
Running `set NODE_PATH=source` from a bat file seems to work in PS and cmd. Check this out: https://github.com/gacosta89/universal-react-boilerplate/pull/1/files

**Comment by vasco3** [comment] 2015-12-15 18:56
solution: not use windows :facepunch:

**Comment by ericelliott** [comment] 2015-12-15 23:58
The correct solution is to introduce something that will set the environment variable in a platform agnostic way. A Windows batch file is the wrong approach.

A better solution is to use a windows bash terminal that supports setting environment variables properly. Have you tried cygwin?

**Comment by ericelliott** [comment] 2015-12-15 23:59
> solution: not use windows

This is a valid solution. Maybe there's a good way to run this in a Docker environment on Windows? It should work fine in any *nix host.

**Comment by LorbusChris** [comment] 2016-01-21 07:01
> set NODE_PATH=source&&babel-node source/server.js

would also work. 
it works on my Win8 just fine thanks to the cross-env lib in the command scripts, though. close?

**Comment by nkbt** [comment] 2016-01-21 11:11
@LorbusChris `set NODE_PATH=source&&babel-node source/server.js` would work, but it does not work on osx/linux. So it is not a solution. `cross-env` is pretty good though and works well on both systems

**Comment by ericelliott** [comment] 2016-01-21 23:32
This should be fixed with https://github.com/cloverfield-tools/universal-react-boilerplate/pull/70

Re-open if it isn't.

**Closed by ericelliott** 2016-01-21 23:32 UTC
Labels: help wanted

**Comment by LorbusChris** [comment] 2016-01-25 17:32
@nktb Yeh I know. I added a dev_windows command to the keystone-test-project a while back ( https://github.com/keystonejs/keystone-test-project/blob/master/package.json#L35 )
Though obvisously with cross-env its way more convenient, ie. just having wach one command run on all OSs. 

Ping @JedWatson, maybe the cross-env lib is sth you'd consider useful in the keystone ecosystem also.

**Comment by nkbt** [comment] 2016-01-26 01:18
@LorbusChris I use cross-env now for all my opensource libs. Pretty good and straightforward
